### ISSUE TITLE
incorrect evaluation on assertions containing intergers list?

### ISSUE THREAD

**Issue by piscvau** [sissaschool/xmlschema#311] opened 2022-06-25 15:09 UTC
Hello
Sorry to come back but I have strong doubts on the evaluation by XMLSchema of the assertions on list. Here is a zip containing 2 files one is considered as valid the other one considered as invalid. The only difference to me is that the incorrect one contains a list for nextsnum which to me should be considered as valid asit contains a list of valid partNumbers 1 and 3. 
Or else the assertion on list is not correct.
[issue_with_list.tar.gz.zip](https://github.com/sissaschool/xmlschema/files/8984982/issue_with_list.tar.gz.zip)
.

**Comment by brunato** [comment] 2022-07-05 14:22
Hi,
it seems that also the _incorrect_with_list.xml_ is good. The problem is the XPath processor (elementpath).
The type is matched but the list is non considered when check the values. I'll try to make a fix for this soon.

Thank you

**Comment by brunato** [comment] 2022-07-18 15:35
Should be fixed in `xmlschema==2.0.0`, and also issue #312.
If is it, close both o reply where the error persists.

Thank you

**Closed** 2022-07-21 10:19 UTC
Labels: bug
