### ISSUE TITLE
xsd:include schemaLocation during testing

### ISSUE THREAD

**Issue by vfilter** [sissaschool/xmlschema#345] opened 2023-04-30 06:49 UTC
Hi,
I'm using Pytest to test a XML schema validation function. The xsd files have been provided to me and consist of a bunch of schemas and a file with common types between all schemas. 

All schema files (in this example `schema_001.xsd`) assume the common type file to be in the same folder (which is true), like so:
`<xsd:include schemaLocation="schema_types.xsd" />`

```
from xmlschema.aliases import SchemaSourceType

schema_001 = open(
    'src/xml_schemas/schema_001.xsd', encoding='utf-8').read()

schema_types = open(
    'src/xml_schemas/schema_types.xsd', encoding='utf-8').read()

merged_schema: list[SchemaSourceType] = [
    schema_001, schema_types]

def validate_data(file_contents: bytes, merged_schema: list[SchemaSourceType]) -> bool:
    return xmlschema.XMLSchema(schema).is_valid(file_contents)
```

The above works when calling the `validate_data()` function from code running in the `/src/` folder, but it doesn't work when using pytest to test the `validate_data()` function.

`XMLSchemaIncludeWarning: Include schema failed: cannot access to resource 'file:///Users/user/dev/project/schema_types.xsd': [Errno 2] No such file or directory: '/Users/user/dev/project/schema_types.xsd'.`

I'm running Pytest from the root of the project, and it is obvious that xmlschema is looking for the `schema_types.xsd` relative to the current working directory instead of relative to the `schema_001.xsd` file.

Changing the `xsd:include schemaLocation` to the relative path of the schema_types.xsd from the project root works, but breaks actual execution of the code.

There is an [interesting answer](https://stackoverflow.com/a/55616129/17483602) on Stackoverflow that mentions a XML Catalog as a potential solution. Don't think that's possible with xmlschema though.

Not sure if this is intended behavior or a bug, but if anyone has any ideas, I would be very grateful.

**Comment by brunato** [comment] 2023-05-04 09:37
Hi,
the warning message explains the *schema_001.xsd* already contains an `xs:include` statement, so it shouldn't be necessary to provide also *schema_types.xsd* schema. 

You provide directly the XSD source texts, so _xmlschema_ does know nothing about schema location. You can alternatively provide the relative path from your project location (`src/xml_schemas/schema_001.xsd`), or the `base_url` (with a `file://` scheme URL).

**Comment by brunato** [comment] 2023-06-26 15:33
This is not a bug and seems to be a misuse of XSD sources, so I close the issue. Reopen if it's not.

**Closed** 2023-06-26 15:34 UTC
