### ISSUE TITLE
Custom validation support

### ISSUE THREAD

**Issue by pekkaklarck** [sissaschool/xmlschema#227] opened 2021-03-08 12:40 UTC
Is it possible to support custom programmatic validation as part of `XMLSchema.validate` or otherwise?

What I want to do in practice is to validate that my schema version (`<xs:schema version="2" ...>`) matches `schemaversion` in my XML file (`<robot schemaversion="2" ...>`). I already noticed I can get the schema version directly from `XMLSchema.version` property and can pretty easily validate that it matches the `schemaversion`. Just wanted to know am I missing an API that would avoid the need to open the XML file myself.

PS: Thanks for creating such a great module to work with schemas! Schemas typically just make me want to cry but this module eases the pain considerably.

**Comment by pekkaklarck** [comment] 2021-03-08 13:24
If you are interested in a concrete example, see here:
https://github.com/robotframework/robotframework/blob/master/atest/resources/TestCheckerLibrary.py#L95

Thanks to `XMLSchema.version` this was pretty easy already now. Feel free to close this issue.

**Comment by brunato** [comment] 2021-03-09 16:00
Hi,

thank you for the appreciations ...

About your question: is not yet available any extra XSD validation method. It would be an interesting idea as an option. There are already other programmatic options in XMLSchema.iter_decode() (_filler_ and _depth_filler_) but an idea for this, similar to the one that you use in robot-framework, should be an extra validators added to XSD components (elements or schema) after the schema building.

This could be a no standard extra validation, so potentially hard to reproduce in other contexts, so i think it should be made on XPath bases and that can be applied autonomously to an XML tree (maybe a collection of paths and associated validation functions).

I leave this open for now if anyone would add other considerations ...
Thank you

**Comment by pekkaklarck** [comment] 2021-03-09 16:05
I was thinking this could work so that  `XMLSchema.validate` gets an optional callable that's called with each etree node in the validated document. Alternatively that method could just return the etree structure that could then be traversed and validated as needed.

**Comment by brunato** [comment] 2021-03-09 21:36
Well, a callable passed to validate method (_iter_decode()_ in fact) could be a generic simple mode to handle this. 
Checking for each element (eg. `if 'extra_validator` in kwargs: ...`) doesn't add relevant burdening to the default validation processing. In this case the callable needs at least two arguments: _elem_ and _xsd_element_ (schema can be retrieved from XSD element ).

Other specifications for this?

**Comment by pekkaklarck** [comment] 2021-03-10 00:48
I was also thinking that getting the XML node and the relevant XSD element would be great. That would have solved my use case and feels like a pretty generic solution as well. It would be handy if the validator could also be passed to the `validate()` method since I believe that's the main API and not everyone knows about `iter_decode()`.

**Comment by brunato** [comment] 2021-03-10 08:20
The argument could be added but the `validate()` method can't return elements because it's based on `iter_decode()` and this is a generator method that yields decoded data and validation errors.

Maybe you can use the `DataElementConverter` (v1.5.0+) for obtaining an _ElementTree_ like data structure with bindings to XSD elements.

**Comment by pekkaklarck** [comment] 2021-03-10 11:47
`validate()` getting support for programmatic validation of the traversed etree nodes would be totally adequate.

**Comment by brunato** [comment] 2021-04-06 09:15
Hi,

in new release v1.6.0 validate methods (`validate()`, `is_valid()` and `iter_errors()`) have an optional argument *extra_validator*.

The argument can be used for providing a two-argument function for doing extra validations. The 1st argument is an Element and the 2nd an XsdElement. This can also be a generator function. The function has to raise/yield `XMLSchemaValidationError` objects.

Please give me a feedback on this and close the issue if this is what is needed.

**Closed** 2021-04-13 07:18 UTC
Labels: enhancement
